default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>


development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'simpleci_dev' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'simpleci_test' %>

production:
  <<: *default
  database: simpleci
